apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
      # annotations:
      #   "config.linkerd.io/proxy-opaque-ports" : "15692"
    spec:
      containers:
      - name: rabbitmq
        image: "{{ .Values.rabbitmq.image }}"
        ports:
        - containerPort: 5672
        - containerPort: 15672
        - containerPort: 15692
        command:
          - /bin/sh
          - -c
          - cp /mnt/definitions.json /opt/ && cp /mnt/rabbitmq.conf /etc/rabbitmq/conf.d/ && docker-entrypoint.sh rabbitmq-server
        env:
        - name: RABBITMQ_ERLANG_COOKIE
          value: "{{ .Values.rabbitmq.env.RABBITMQ_ERLANG_COOKIE }}"
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: rabbitmq-user
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: rabbitmq-password
        - name: RABBITMQ_LOGS
          value: "{{ .Values.rabbitmq.env.RABBITMQ_LOGS }}"
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
        - name: rabbitmq-log
          mountPath: /var/log/rabbitmq
        - name: rabbitmq-config
          mountPath: /mnt
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim:
            claimName: rabbitmq-data-pvc
      - name: rabbitmq-log
        persistentVolumeClaim:
            claimName: rabbitmq-log-pvc
      - name: rabbitmq-config
        persistentVolumeClaim:
          claimName: rabbit-pvc
