Namespace: core
tracingEndpoint: collector.linkerd-jaeger:55678

rabbitmq:
  image: rabbitmq:3-management
  ports:
    - 5672:5672
    - 15672:15672
  env:
    RABBITMQ_ERLANG_COOKIE: "mysecretcookie"
    RABBITMQ_DEFAULT_USER: "guest"
    RABBITMQ_DEFAULT_PASS: "guest"
    RABBITMQ_LOGS: "-"

hostPath: default

etcd:
  nodeName: 0
  replicaCount: 3
  image:
    repository: quay.io/coreos/etcd
    tag: v3.5.1
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP


loki:
  image: grafana/loki:2.8.0
  port: "3100"

promtail:
  image: grafana/promtail:2.8.0

grafana:
  image: grafana/grafana:latest
  ports:
    - 3000:3000
