apiVersion: apps/v1
kind: Deployment
metadata:
  name: vu
  namespace: vu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vu
  template:
    metadata:
      labels:
        app: vu
      annotations:
        "linkerd.io/inject" : enabled
    spec:
      serviceAccountName: job-creator-vu
      containers:
      - name: vu
        image: jorrit05/dynamos-agent:{{ .Values.branchNameTag }}
        imagePullPolicy: Always
        env:
        - name: DATA_STEWARD_NAME
          value: VU
        - name: OC_AGENT_HOST
          value: {{ .Values.tracingEndpoint }}
      - name: sidecar
        image: jorrit05/dynamos-sidecar:{{ .Values.branchNameTag }}
        imagePullPolicy: Always
        env:
        - name: AMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rabbit
              key: password
        - name: AMQ_USER
          value: normal_user
        - name: OC_AGENT_HOST
          value: {{ .Values.tracingEndpoint }}

---

apiVersion: v1
kind: Service
metadata:
  name: vu
  namespace: vu
spec:
  selector:
    app: vu
  ports:
    - name: http-vu-api
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vu-ingress
  namespace: vu
  annotations:
    nginx.ingress.kubernetes.io/service-upstream: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: vu.vu.svc.cluster.local
    http:
      paths:
      - pathType: Prefix
        path: "/agent/v1/sqlDataRequest/vu"
        backend:
          service:
            name: vu
            port:
              number: 8080